apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
- includeSelectors: true
  pairs:
    varient: caas
commonAnnotations:
  note: CaaS varients
resources:
- ../../base
patches:
- path: ./ci_image.yaml
- path: ./replicas.yaml
- path: ./probes.yaml
- path: ./registry_credentials.yaml
