apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: style-lab
spec:
  template:
    spec:
      containers:
        - name: style-lab
          readinessProbe:
            httpGet:
              path: /style-lab/
              port: 80
            initialDelaySeconds: 5
            timeoutSeconds: 1
            periodSeconds: 15
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 15
            timeoutSeconds: 1
            periodSeconds: 15
