stages:
  - build
  - deploy

# Can't use the {::8} notation to get a short sha in the variables section, so exporting below
before_script:
  - export CI_COMMIT_SHA_SHORT=${CI_COMMIT_SHA::8}
  - export IMAGE_NAME=$CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG:$CI_COMMIT_SHA_SHORT

build_docker:
  image: docker:stable
  stage: build
  tags:
    - dind
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -t $IMAGE_NAME .
    - docker push $IMAGE_NAME

# Reusable template, requires the $KUBE_CONFIG and $NAMESPACE variables to be set
# This subsitutes the environment variable $IMAGE_NAME in the overlay file, and deploys
.template: &deploy
  image: ebiwd/alpine-ssh:latest
  script:
    - mkdir -p $HOME/.kube
    - echo -n $KUBE_CONFIG | base64 -d > $HOME/.kube/config
    - envsubst '$IMAGE_NAME' < k8s/overlays/caas/ci_image.yaml > file.tmp && mv file.tmp k8s/overlays/caas/ci_image.yaml
    - kubectl kustomize k8s/overlays/caas/ | kubectl --namespace=$NAMESPACE apply -f -

deploy_to_hh_wp_dev:
  stage: deploy
  only:
    - master
  variables:
    NAMESPACE: static-sites-dev
    KUBE_CONFIG: $HH_WP_KUBE_CONFIG
  <<: *deploy

deploy_to_hx_wp_dev:
  stage: deploy
  only:
    - master
  variables:
    NAMESPACE: static-sites-dev
    KUBE_CONFIG: $HX_WP_KUBE_CONFIG
  <<: *deploy

deploy_to_hh_wp_prod:
  stage: deploy
  only:
    - tags
  variables:
    NAMESPACE: static-sites-prod
    KUBE_CONFIG: $HH_WP_KUBE_CONFIG
  <<: *deploy

deploy_to_hx_wp_prod:
  stage: deploy
  only:
    - tags
  variables:
    NAMESPACE: static-sites-prod
    KUBE_CONFIG: $HX_WP_KUBE_CONFIG
  <<: *deploy
