image: ebiwd/alpine-ssh:3.6

#project specific variables can be defined here, or overridden project settings
variables:
  DEV_SERVER: ebi-cli
  DEV_DEST: /nfs/public/rw/webdevel/projects/static/test/wwwdev.ebi.ac.uk/style-lab
  DEV_URL: http://wwwdev.ebi.ac.uk/style-lab

  PROD_SERVER: ebi-cli pg-001
  PROD_DEST: /nfs/public/rw/webdevel/projects/static/live/www.ebi.ac.uk/style-lab
  PROD_URL: http://www.ebi.ac.uk/style-lab

  SSH_OWNER: wd_adm

# do not define here, put in project variables
  SSH_OWNER_KEY: secret-key

stages:
  - build
  - deploy

build:
  stage: build
  image: ebiwd/node-bower-gulp:6
  before_script:
    - cd ${CI_PROJECT_DIR}
    - npm install --quiet
    - bower --allow-root install --quiet
  script:
    - npm run build
  cache:
    paths:
      - node_modules
      - bower_components
  artifacts:
    paths:
      - dist

#setup ssh keys
.deploy_setup: &deploy_setup
  before_script:
    - add-ssh-key ${SSH_OWNER} "${SSH_OWNER_KEY}"
    - add-search-domain ebi.ac.uk

deploy_dev: &deploy
  <<: *deploy_setup
  variables:
    NAME: dev
    URL: ${DEV_URL}
    DEST: ${DEV_DEST}
    VMS: ${DEV_SERVER}
  stage: deploy
  script:
    - for VM in ${VMS}; do
        rsync -acv --delete-after ${CI_PROJECT_DIR}/dist/. ${SSH_OWNER}@${VM}:${DEST}/;
      done
  only:
    - master
  environment:
    name: ${NAME}
    url: ${URL}

deploy_live:
  <<: *deploy
  only:
    - tags
  variables:
    NAME: live
    URL: ${PROD_URL}
    DEST: ${PROD_DEST}
    VMS: ${PROD_SERVER}
