language: node_js

node_js:
  - "12"

install:
  - npm install

before_script:
  - npm install -g bower
  - bower install

script: npm run build

# deploy:
#   provider: pages
#   skip_cleanup: true
#   target_branch: gh-pages
#   github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
#   local_dir: dist
#   on:
#     branch: master
