apiVersion: v1
kind: Service
metadata:
  name: style-lab-service
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    app: style-lab
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: style-lab
spec:
  selector:
    matchLabels:
      app: style-lab
  replicas: 1
  template:
    metadata:
      labels:
        app: style-lab
    spec:
      containers:
        - name: style-lab
          image: style-lab:latest
          ports:
            - containerPort: 8080
